kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-app
    spec:
      volumes:
        - name: my-volume
          emptyDir: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: frontend-app
          env:
            - name: d
              value: d
            - name: elastic.apm.server-url
              value: " http://apm-server-test.apps.ocp4.pacosta.com"
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: my-volume
              mountPath: /data
          terminationMessagePolicy: File
          image: "registry.ocp4.pacosta.com:8443/test/frontendeoffice:v28"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: worker16.ocp4.pacosta.com
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 61
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: "True"
      lastUpdateTime: "2023-12-11T04:21:23Z"
      lastTransitionTime: "2023-12-11T04:21:23Z"
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: "True"
      lastUpdateTime: "2023-12-11T04:34:01Z"
      lastTransitionTime: "2023-09-21T05:34:06Z"
      reason: NewReplicaSetAvailable
      message: ReplicaSet "frontend-deployment-66695c7c75" has successfully progressed.
